# config.py

# Security
MIN_PASSWORD_LENGTH = 8
MIN_USERNAME_LENGTH = 3
JWT_EXPIRES_HOURS_ADMIN = 12
JWT_EXPIRES_HOURS_USER = 8

# Pagination
MAX_ITEMS_PER_PAGE = 100
DEFAULT_ITEMS_PER_PAGE = 10

# File Uploads
MAX_CONTENT_LENGTH = 50 * 1024 * 1024  # 50 MB
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'pdf'}
